/* SPDX-License-Identifier: Apache-2.0 */
/* Generated by cbindgen from bindings/c/src/lib.rs — do not edit by hand. */

#ifndef RFL_H
#define RFL_H

/* This file is auto-generated; regenerate with `cargo build -p rfl-c`. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Retarget a Skill ISA composition onto an embodiment descriptor.
 *
 * `skill_yaml` and `descriptor_yaml` are NUL-terminated UTF-8 strings. On
 * success `*ok` is set to `true` and the return value is the canonical JSONL
 * (one `execute` message per line). On a parse/retarget failure `*ok` is set to
 * `false` and the return value is a human-readable error message. The returned
 * pointer is owned by the caller and must be freed with [`rfl_string_free`].
 *
 * Returns null only if `skill_yaml` or `descriptor_yaml` is null.
 *
 * # Safety
 * `skill_yaml` and `descriptor_yaml` must each be either null or a valid pointer
 * to a NUL-terminated string that stays valid for the duration of the call.
 * `ok` must be either null or a valid pointer to a writable `bool`.
 */
char *rfl_retarget(const char *skill_yaml, const char *descriptor_yaml, bool *ok);

/**
 * Free a string returned by [`rfl_retarget`].
 *
 * # Safety
 * `s` must be either null or a pointer previously returned by [`rfl_retarget`]
 * and not yet freed. Passing any other pointer, or freeing twice, is undefined
 * behavior.
 */
void rfl_string_free(char *s);

/**
 * The specification version this build implements (e.g. `v0.1-draft`).
 *
 * Returns a pointer to a static NUL-terminated string; do NOT free it.
 */
const char *rfl_spec_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RFL_H */
